// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Inicie a conversa"
          text="Pronto para automatizar seu atendimento e elevar sua presença digital?"
          primaryButton={{
            text: "Chamar no WhatsApp",
            href: "https://wa.me/5500000000000",
          }}
          secondaryButton={{
            text: "Fale por Email",
            href: "mailto:contato@esqipi.com.br",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
