// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitVerticalMarquee from '@/components/sections/hero/HeroSplitVerticalMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitVerticalMarquee
          tag="Inovação para seu negócio"
          title="Menos demanda pra sua empresa, inteligência pro seu negócio."
          description="Transformamos processos complexos em conversas ágeis. Conecte-se com seu cliente de forma inteligente e automática."
          primaryButton={{
            text: "Fale no WhatsApp",
            href: "https://wa.me/5541988338255",
          }}
          secondaryButton={{
            text: "Conheça mais",
            href: "#about",
          }}
          leftItems={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-abstract-background-with-low-poly-network-communications-design_1048-15812.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-abstract-particle-background_1048-11982.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-render-abstract-particle-design-space-nebula-background_1048-13250.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-render-network-communications-design-background-with-shallow-depth-field_1048-14612.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-render-digital-technology-background-with-lcd-design_1048-15284.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-abstract-background-with-flowing-waves-particles_1048-18061.jpg",
            },
          ]}
          rightItems={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/artistic-blurry-colorful-wallpaper-background_58702-10129.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/abstract-background-with-low-poly-plexus-design_1048-15841.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-geometric-shapes_23-2150979717.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/green-abstract-background_23-2151820772.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-render-flowing-particles-science-background-with-shallow-depth-field_1048-14039.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/create-website-layout-blank-banner_53876-132284.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
