// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "how-it-works" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HowItWorksSection(): React.JSX.Element {
  return (
    <div id="how-it-works" data-section="how-it-works">
        <SectionErrorBoundary name="how-it-works">
              <FaqSplitMedia
          tag="Processo"
          title="Como trabalhamos"
          description="Simples, rápido e eficiente para o seu sucesso."
          items={[
            {
              question: "1. Diagnóstico",
              answer: "Entendemos seu modelo de negócio e principais gargalos.",
            },
            {
              question: "2. Desenvolvimento",
              answer: "Implementamos seu site ou sistema de automação.",
            },
            {
              question: "3. Otimização",
              answer: "Testamos e refinamos para máxima performance.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/joyful-businesswoman-talking-with-remote-friend-online-videocall_482257-77662.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
