// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "portfolio" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PortfolioSection(): React.JSX.Element {
  return (
    <div id="portfolio" data-section="portfolio">
        <SectionErrorBoundary name="portfolio">
              <FeaturesRevealCardsBento
          tag="Portfólio"
          title="Projetos de impacto"
          description="Veja como ajudamos empresas a transformar sua presença digital."
          items={[
            {
              title: "Site Corporativo",
              description: "Portal completo para indústria.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/7654168/pexels-photo-7654168.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=7654168",
            },
            {
              title: "Processo automatizado de leads.",
              description: "Automação integrada ao sistema.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/9784240/pexels-photo-9784240.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=9784240",
            },
            {
              title: "Landing Page SaaS",
              description: "Alta conversão para leads.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/female-web-designer-office_23-2149749873.jpg",
            },
            {
              title: "E-commerce Premium",
              description: "Loja virtual de alta performance.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/5560606/pexels-photo-5560606.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=5560606",
            },
            {
              title: "Portal de ",
              description: "Gestão de agendamentos.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/8439002/pexels-photo-8439002.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=8439002",
            },
            {
              title: "Blog Tech",
              description: "Conteúdo especializado e moderno.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/4389465/pexels-photo-4389465.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=4389465",
            },
            {
              title: "Dashboard Analítico",
              description: "Visualização de dados automatizada.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/research-analysis-ideas-strategy-information-concept_53876-123886.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
