// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBorderGlow from '@/components/sections/features/FeaturesBorderGlow';
import { Globe, Layout, MessageSquare } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesBorderGlow
          tag="Especialidades"
          title="Soluções que geram resultados"
          description="Tecnologia de ponta para empresas que buscam automação real e presença digital memorável."
          features={[
            {
              icon: Globe,
              title: "Criação de Sites",
              description: "Sites modernos, rápidos e focados em alta conversão.",
            },
            {
              icon: MessageSquare,
              title: "Automação WhatsApp",
              description: "Atendimento automático 24/7 que converte leads em vendas.",
            },
            {
              icon: Layout,
              title: "Landing Pages",
              description: "Páginas otimizadas para capturar e converter seus visitantes.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
