// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialRatingCards from '@/components/sections/testimonial/TestimonialRatingCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialRatingCards
          tag="Depoimentos"
          title="O que dizem sobre nós"
          description="Resultados reais para empresas que confiam na nossa automação."
          testimonials={[
            {
              name: "Wendryll Moraes",
              role: "CEO",
              quote: "A automação dobrou nossos leads.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/picture-attractive-caucasian-man-with-money-pocket_176420-7260.jpg",
            },
            {
              name: "João Mello Souza",
              role: "Marketing",
              quote: "O site ficou impecável e muito rápido.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-handsome-smiling-stylish-hipster-lambersexual-modelsexy-modern-man-dressed-elegant-suit-fashion-male-posing-studio-near-blue-wall_158538-21048.jpg",
            },
            {
              name: "Carlos Lima",
              role: "Founder",
              quote: "Atendimento nota 10, muito ágeis.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/handsome-bearded-african-american-businessman-brown-classic-jacket-isolated-dark-background_613910-6551.jpg",
            },
            {
              name: "Thiago Reis",
              role: "Gerente",
              quote: "Processo transparente e muito eficiente.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-young-businessman-suit-looking-camera-meeting_1163-4654.jpg",
            },
            {
              name: "Pedro Santos",
              role: "Engenheiro",
              quote: "Excelente entrega de tecnologia.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-handsome-young-man-with-arms-crossed-holding-white-headphone-around-his-neck_23-2148096439.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
